{{ if .Values.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cifs-pvc.fullname" . }}
  labels:
{{ include "cifs-pvc.labels" . | indent 4 }}
type: juliohm/cifs
data:
  password: {{ required "password is required" .Values.password | b64enc | quote }}
  username: {{ required "username is required" .Values.username | b64enc | quote }}
{{- end }}
