apiVersion: v1
kind: PersistentVolume
metadata:
  name: boxids-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: sec=ntlm,uid=1000
      server: xxxxx
      share: /xxxxxxx
    secretRef:
      name: xxxxx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: boxids-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
