strategy:
  type: Recreate

ingress:
  enabled: true
  hosts: ['t.g4v.dev']
  tls:
    - secretName: psitransfer-tls
      hosts: ['t.g4v.dev']
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k

persistence:
  enabled: true
  storageClassName: "longhorn"
  size: 20Gi

