---
ingress:
  enabled: true
  tls:
    - secretName: guacamole-tls
      hosts:
        - guacamole.home.gavinmogan.com
  hosts:
    - host: guacamole.home.gavinmogan.com
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/app-root: /guacamole
