#repositories:
#  - name: halkeye
#    url: https://halkeye.github.io/helm-charts
#releases:
#  - name: firefly-iii
#    chart: halkeye/firefly-iii
#    namespace: firefly-iii
#    values:
#      - firefly-iii.yaml
#    secrets:
#      - firefly-iii-secrets.yaml
