repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: pterodactyl-panel
    #chart: halkeye/pterodactyl-panel
    chart: /home/halkeye/git/halkeye-helm-charts/pterodactyl-panel
    namespace: games
    values:
      - pterodactyl-panel.yaml
    secrets:
      - pterodactyl-panel-secrets.yaml
  #- name: sevendaysdie
  #  chart: halkeye/sevendaysdie
  #  namespace: sevendaysdie
  #  values:
  #    - 7daystodie.yaml
  #  secrets:
  #    - 7daystodie-secrets.yaml
  #- name: terraria
  #  chart: halkeye/terraria
  #  namespace: games
  #  values:
  #    - terraria.yaml
  #  secrets:
  #    - terraria-secrets.yaml
  #- name: dontstarvetogether
  #  chart: halkeye/dontstarvetogether
  #  namespace: games
  #  values:
  #    - dontstarvetogether.yaml
  #  secrets:
  #    - dontstarvetogether-secrets.yaml
