repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: gamedeals-bot
    chart: ../../charts/discord-gamedeals-bot
    namespace: discord-bots
    secrets:
      - gamedeals-bot-secrets.yaml
