repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: gamedeals-bot
    chart: ../../charts/discord-gamedeals-bot
    namespace: discord-bots
    secrets:
      - gamedeals-bot-secrets.yaml
  #- name: discord-rpg-schedule
  #  chart: ../../charts/discord-rpg-schedule
  #  namespace: discord-bots
  #  values:
  #    - discord-rpg-schedule.yaml
  #  secrets:
  #    - discord-rpg-schedule-secrets.yaml
  - name: discord-streamers
    chart: halkeye/discord-streamers
    namespace: discord-streamers
    values:
      - discord-streamers.yaml
    secrets:
      - discord-streamers-secrets.yaml
