releases:
  - name: wallabag
    #chart: halkeye/wallabag
    chart: /home/halkeye/git/halkeye-helm-charts/wallabag
    namespace: wallabag
    values:
      - ./wallabag.yaml
    secrets:
      - ./wallabag-secrets.yaml
