repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: comics
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          share: /storage/Comics

  - name: books
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          share: /storage/Books

  - name: torrents
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          share: /storage/storage/downloads

  - name: cops
    chart: halkeye/cops
    #chart: /home/halkeye/git/halkeye-helm-charts/cops
    namespace: media
    values:
      - cops.yaml

  - name: tautulli
    chart: halkeye/tautulli
    #chart: /home/halkeye/git/halkeye-helm-charts/tautulli
    namespace: media
    values:
      - tautulli.yaml
    secrets:
      - tautulli-secrets.yaml

  - name: ubooquity
    chart: halkeye/ubooquity
    namespace: media
    values:
      - ubooquity.yaml

  - name: zap2xml
    chart: ../../charts/zap2xml
    namespace: media
    secrets:
      - zap2xml-secret.yaml

  - name: nzbhydra2
    chart: k8s-at-home/nzbhydra2
    namespace: media
    values:
      - nzbhydra2.yaml

  - name: qbittorrent
    chart: k8s-at-home/qbittorrent
    namespace: media
    values:
      - qbittorrent.yaml

  - name: jackett
    chart: halkeye/jackett
    namespace: media
    values:
      - jackett.yaml

#  - name: radarr
#    chart: k8s-at-home/radarr
#    namespace: media
#    values:
#      - radarr.yaml
#
#  - name: sonarr
#    chart: k8s-at-home/sonarr
#    namespace: media
#    values:
#      - sonarr.yaml

#  - name: mylar-downloads
#    namespace: media
#    chart: ../../charts/nfs-pvc
#    values:
#      - pv:
#          share: /storage/storage/downloads/Comics
#
#  - name: mylar3
#    chart: /home/halkeye/git/halkeye-helm-charts/mylar3
#    namespace: media
#    values:
#      - mylar3.yaml
#
#  - name: comics-downloads
#    namespace: media
#    chart: ../../charts/nfs-pvc
#    values:
#      - pv:
#          share: /storage/storage/downloads/Comics
#
#  - name: readarr
#    chart: /home/halkeye/git/halkeye-helm-charts/readarr
#    namespace: media
#    values:
#      - readarr.yaml
