#helmDefaults:
#  atomic: true

repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: comics
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Comics

  - name: comics-cifs
    namespace: media
    chart: ../../charts/cifs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /Comics
          uid:
          gid:

  - name: books
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Books

  - name: tv
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/TV

  - name: movies
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Movies

  - name: anime
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Anime

  - name: anime-movies
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Anime Movies

  - name: webseries
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Webseries

  - name: webseries-movies
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Webseries Movies

  - name: torrents
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Apps/torrents

  - name: nzbs
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: /volume1/Apps/nzbget

  - name: audiobooks
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: "/volume1/Audio/Audio Books"

  - name: music
    namespace: media
    chart: ../../charts/nfs-pvc
    values:
      - pv:
          server: 172.16.10.10
          share: "/volume1/Audio/Music"

  - name: tautulli
    #chart: halkeye/tautulli
    chart: /home/halkeye/git/halkeye-helm-charts/tautulli
    namespace: media
    values:
      - tautulli.yaml
    secrets:
      - tautulli-secrets.yaml

  - name: ubooquity
    #chart: halkeye/ubooquity
    chart: /home/halkeye/git/halkeye-helm-charts/ubooquity
    namespace: media
    values:
      - ubooquity.yaml

  - name: zap2xml
    chart: ../../charts/zap2xml
    namespace: media
    secrets:
      - zap2xml-secret.yaml

  - name: nzbhydra2
    chart: k8s-at-home/nzbhydra2
    namespace: media
    values:
      - nzbhydra2.yaml

  - name: qbittorrent
    chart: k8s-at-home/qbittorrent
    namespace: media
    values:
      - qbittorrent.yaml

  - name: nzbget
    chart: k8s-at-home/nzbget
    namespace: media
    values:
      - nzbget.yaml

  - name: prowlarr
    chart: k8s-at-home/prowlarr
    namespace: media
    values:
      - prowlarr.yaml

  - name: jackett
    chart: halkeye/jackett
    namespace: media
    values:
      - jackett.yaml

  - name: bazarr
    chart: k8s-at-home/bazarr
    namespace: media
    values:
      - bazarr.yaml

  - name: calibre-web
    chart: k8s-at-home/calibre-web
    namespace: media
    values:
      - calibre-web.yaml

  - name: overseerr
    chart: k8s-at-home/overseerr
    namespace: media
    values:
      - overseerr.yaml

  - name: radarr
    chart: k8s-at-home/radarr
    namespace: media
    values:
      - radarr.yaml

  - name: sonarr
    chart: k8s-at-home/sonarr
    namespace: media
    values:
      - sonarr.yaml

  - name: lidarr
    chart: k8s-at-home/lidarr
    namespace: media
    values:
      - lidarr.yaml

#  - name: mylar3
#    chart: /home/halkeye/git/halkeye-helm-charts/mylar3
#    namespace: media
#    values:
#      - mylar3.yaml
#
  #- name: readarr
  #  chart: k8s-at-home/readarr
  #  namespace: media
  #  values:
  #    - readarr.yaml
