repositories:
  - name: jellyfin
    url: git+https://github.com/brianmcarey/jellyfin-helm@?ref=master
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: media-cifs-secret
    chart: ../../charts/cifs-secret
    namespace: media
    secrets:
      - cifs-secret.yaml

  - name: radarr-storage-movies
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /movies

  - name: radarr-storage-anime-movies
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /AnimeMovies

  - name: radarr-storage-comedian-specials
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /ComedianSpecials

  - name: radarr-downloads
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /downloads/Movies


  - name: sonarr-storage-tv
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /TV

  - name: sonarr-storage-anime
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /Anime

  - name: sonarr-storage-webseries
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /Webseries

  - name: sonarr-downloads
    namespace: media
    chart: ../../charts/cifs-pvc
    secrets:
      - cifs-pvc-secrets.yaml
    values:
      - pv:
          share: /downloads/TV

  - name: cops
    chart: halkeye/cops
    namespace: media
    values:
      - cops.yaml

  - name: ubooquity
    chart: halkeye/ubooquity
    namespace: media
    values:
      - ubooquity.yaml

  #- name: jellyfin
  #  chart: jellyfin/jellyfin
  #  namespace: media
  #  values:
  #    - jellyfin.yaml

  - name: zap2xml
    chart: ../../charts/zap2xml
    namespace: media
    secrets:
      - zap2xml-secret.yaml

  - name: nzbhydra2
    chart: k8s-at-home/nzbhydra2
    namespace: media
    values:
      - nzbhydra2.yaml

  - name: jackett
    chart: halkeye/jackett
    namespace: jackett
    values:
      - jackett.yaml

  - name: radarr
    chart: k8s-at-home/radarr
    namespace: media
    values:
      - radarr.yaml

  - name: sonarr
    chart: k8s-at-home/sonarr
    namespace: media
    values:
      - sonarr.yaml
