{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "powerdns-recursor.serviceAccountName" . }}
  labels:
{{ include "powerdns-recursor.labels" . | indent 4 }}
{{- end -}}
