releases:
  - name: home
    namespace: proxies
    chart: ../../charts/proxy-endpoint
    values:
      - home.yaml
  - name: pikvm
    namespace: proxies
    chart: ../../charts/proxy-endpoint
    values:
      - pikvm.yaml
