ingress:
  enabled: true
  hosts:
    - turtl.gavinmogan.com
    - turtl.home.gavinmogan.com
  tls:
    - secretName: turtl-tls
      hosts:
        - turtl.gavinmogan.com
        - turtl.home.gavinmogan.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  storageClassName: linstor
