repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: redis
    chart: stable/redis
    namespace: default
    values:
      - redis.yaml
    secrets:
      - ../../secrets/redis.yaml
  - name: postgresql
    chart: ../../charts/postgresql
    namespace: default
    values:
      - postgresql.yaml
    secrets:
      - postgresql-secret.yaml
  - name: pgadmin
    chart: halkeye/pgadmin
    namespace: default
    values:
      - pgadmin.yaml
    secrets:
      - pgadmin-secret.yaml
  - name: mongodb
    chart: bitnami/mongodb
    namespace: databases
    values:
      - mongodb.yaml
    secrets:
      - mongodb-secrets.yaml
