repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: influxdata
    url: https://helm.influxdata.com/
  - name: bitnami
    url: https://charts.bitnami.com/

releases:
  - name: redis
    chart: stable/redis
    namespace: default
    values:
      - redis.yaml
    secrets:
      - redis-secrets.yaml
  - name: postgresql
    chart: ../../charts/postgresql
    namespace: default
    values:
      - postgresql.yaml
    secrets:
      - postgresql-secret.yaml
  - name: pgadmin
    chart: halkeye/pgadmin
    namespace: default
    values:
      - pgadmin.yaml
    secrets:
      - pgadmin-secret.yaml
  - name: influxdb
    chart: influxdata/influxdb
    namespace: databases
    values:
      - influxdb.yaml
  #- name: mongodb
  #  chart: bitnami/mongodb
  #  namespace: databases
  #  values:
  #    - mongodb.yaml
  #  secrets:
  #    - mongodb-secrets.yaml
