releases:
  - name: openldap
    chart: ../../charts/openldap
    namespace: openldap
    values:
      - openldap.yaml
    secrets:
      - openldap-secrets.yaml
  #- name: selfservice
  #  chart: halkeye/ldap-self-service
  #  namespace: openldap
  #  values:
  #    - selfservice.yaml
  #  secrets:
  #    - ../../secrets/selfservice.yaml
