fireflyiii:
  url: 'https://money.g4v.dev'

persistence:
  enabled: true
  storageClassName: linstor
  accessModes:
    - ReadWriteMany
  size: 1Gi

ingress:
  enabled: true
  hosts:
    - host: money.g4v.dev
      paths: ['/']
  tls:
    - secretName: fireflyiii-tls
      hosts:
        - money.g4v.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
