repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

helmDefaults:
  cleanupOnFail: true

releases:
  - name: synapse
    chart: halkeye/synapse
    namespace: matrix
    values:
      - ./synapse.yaml
    secrets:
      - ./synapse-secret.yaml

  - name: riot-im
    chart: halkeye/element-im
    namespace: matrix
    values:
      - ./riot-im.yaml

  - name: matrix-media-repo
    chart: halkeye/matrix-media-repo
    namespace: matrix
    values:
      - ./matrix-media-repo.yaml
    secrets:
      - ./matrix-media-repo-secret.yaml

  - name: mautrix-whatsapp
    chart: halkeye/mautrix-whatsapp
    namespace: matrix
    values:
      - ./mautrix-whatsapp.yaml
    secrets:
      - ./mautrix-whatsapp-secret.yaml

  - name: mautrix-telegram
    chart: halkeye/mautrix-telegram
    namespace: matrix
    values:
      - ./mautrix-telegram.yaml
    secrets:
      - ./mautrix-telegram-secret.yaml

  - name: matrix-dimension
    chart: halkeye/matrix-dimension
    namespace: matrix
    values:
      - ./matrix-dimension.yaml
    secrets:
      - ./matrix-dimension-secret.yaml

  - name: mautrix-hangouts
    chart: halkeye/mautrix-hangouts
    namespace: matrix
    values:
      - ./mautrix-hangouts.yaml
    secrets:
      - ./mautrix-hangouts-secret.yaml
