repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: unifi
    chart: k8s-at-home/unifi
    namespace: unifi
    values:
      - unifi.yaml
    secrets:
      - unifi-secrets.yaml
  - name: unifi-poller
    chart: /home/halkeye/git/halkeye-helm-charts/unifi-poller
    namespace: unifi
    values:
      - unifi-poller.yaml
    secrets:
      - unifi-poller-secrets.yaml
