apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-gamedeals-bot.fullname" . }}
  labels:
{{ include "discord-gamedeals-bot.labels" . | indent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "need database_url" .Values.database_url | toString | b64enc | quote }}
  ADMIN_USER_ID: {{ .Values.admin_user_id | toString | b64enc | quote }}
  CLIENT_ID: {{ required "need bot app in discord_client_id" .Values.discord_client_id | toString | b64enc | quote }}
  BOT_TOKEN: {{ required "need bot_token" .Values.bot_token | toString | b64enc | quote }}
