{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "discord-gamedeals-bot.serviceAccountName" . }}
  labels:
{{ include "discord-gamedeals-bot.labels" . | indent 4 }}
{{- end -}}
