releases:
  - name: postgresql
    #chart: stable/postgresql
    chart: ../../charts/postgresql
    namespace: default
    values:
      - postgresql.yaml
    secrets:
      - postgresql-secret.yaml
  - name: pgadmin
    chart: halkeye/pgadmin
    namespace: default
    values:
      - pgadmin.yaml
    secrets:
      - pgadmin-secret.yaml
