---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "nfs-pvc.fullname" . }}
  labels:
{{ include "nfs-pvc.labels" . | indent 4 }}
spec:
  storageClassName: ""
  volumeName: {{ include "nfs-pvc.fullname" . }}
  accessModes:
{{ .Values.pvc.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
