ingress:
  enabled: true
  tls:
    - secretName: synapse-tls
      hosts:
        - matrix.g4v.dev
  hosts:
    - host: matrix.g4v.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
config:
  matrix:
    domain: g4v.dev
    v1: true   # deprecated
    v2: true  # MSC2140 API v2. Disabled by default in order to preserve backward compatibility.
  server:
    name: matrix.g4v.dev
    publicUrl: https://matrix.g4v.dev
  storage:
    backend: postgresql
    provider:
      postgresql:
        database: '//postgresql.default.svc.cluster.local:5432/ma1sd'
        username: ma1sd
  forward:
    servers:
      - vector.im
      - matrix.org
  threepid:
    medium:
      email:
        identity:
          # The e-mail to send as.
          from: "matrix-identity@g4v.dev"
        connectors:
          smtp:
            # SMTP host
            host: "odin.dhcp.home"
            tls: 0
            port: 25
    synapseSql:
      #connection: //postgresql.default.svc.cluster.local/synapse?user=synapse&password=[redacted]
      lookup:
        # query for retrive 3PIDs for hashes.
        query: 'select user_id as mxid, medium, address from user_threepids'
    ldap:
      enabled: true
      lookup: true # hash lookup
      connection:
        host: openldap.openldap.svc.cluster.local
        port: 389
        bindDn: cn=admin,dc=gavinmogan,dc=com
        # bindPassword: [redacted]
        baseDNs:
          - 'ou=users,dc=gavinmogan,dc=com'
      attribute:
        uid:
          type: 'uid' # or mxid
          value: 'uid'
        name: 'displayName'
        email: 'mail'
      identity:
        filter: '(objectClass=inetOrgPerson)'
