ingress:
  enabled: true
  tls:
    - secretName: synapse-tls
      hosts:
        - matrix.g4v.dev
  hosts:
    - host: matrix.g4v.dev
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

strategy:
  type: Recreate

homeserver:
  server_name: "g4v.dev"
  admin_contact: 'mailto:matrix@g4v.dev'
  enable_registration: false
  public_baseurl: https://matrix.g4v.dev/
  email:
    enable_notifs: false
    notif_from: "Your Friendly %(app)s homeserver <noreply@g4v.dev>"
    #app_name: my_branded_matrix_server
    client_base_url: "http://chat.g4v.dev"
  saml2_config:
    idp_redirect_url: "https://keycloak.g4v.dev/auth/realms/master/protocol/saml"
    sp_config:
      entityid: "matrix-g4v-dev"
      description: "Matrix Server"
      metadata:
        remote:
          - url: https://keycloak.g4v.dev/auth/realms/master/protocol/saml/descriptor
      debug: 0
      key_file: "/config/saml-key.pem"
      cert_file: "/config/saml-cert.pem"
      encryption_keypairs:
        - key_file: "/config/saml-key.pem"
          cert_file: "/config/saml-cert.pem"
      attribute_map_dir: "/config/"
      xmlsec_binary: "/usr/bin/xmlsec1"
      name_form: "urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
      service:
        sp:
          name: "matrix-login"
          endpoints:
            single_sign_on_service:
              - "https://matrix.g4v.dev/_matrix/saml2/authn_response"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            assertion_consumer_service:
              - "https://matrix.g4v.dev/_matrix/saml2/authn_response"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            single_logout_service:
              - "https://matrix.g4v.dev/_matrix/saml2/logout"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
          required_attributes: ["uid", "mail"]
          optional_attributes: ["displayName"]
          sign_assertion: true
          sign_response: true
          allow_unsolicited: true

dnsConfig:
  options:
    - name: ndots
      value: "1"
