ingress:
  enabled: true
  tls:
    - secretName: synapse-tls
      hosts:
        - matrix.g4v.dev
  hosts:
    - host: matrix.g4v.dev
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

strategy:
  type: Recreate

homeserver:
  server_name: "g4v.dev"
  admin_contact: 'mailto:matrix@g4v.dev'
  enable_registration: false
  public_baseurl: https://matrix.g4v.dev/
  email:
    enable_notifs: false
    notif_from: "Your Friendly %(app)s homeserver <noreply@g4v.dev>"
    #app_name: my_branded_matrix_server
    client_base_url: "http://chat.g4v.dev"
  #password_providers:
  #    - module: "ldap_auth_provider.LdapAuthProvider"
  #      config:
  #        enabled: true
  #        uri: "ldap://ldap.example.com:389"
  #        start_tls: true
  #        base: "ou=users,dc=example,dc=com"
  #        attributes:
  #           uid: "cn"
  #           mail: "email"
  #           name: "givenName"
  #        #bind_dn:
  #        #bind_password:
  #        #filter: "(objectClass=posixAccount)"

dnsConfig:
  options:
    - name: ndots
      value: "1"
