ingress:
  enabled: true
  tls:
    - secretName: synapse-tls
      hosts:
        - matrix.g4v.dev
  hosts:
    - host: matrix.g4v.dev
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"

cacheFactor: 5.0

homeserver:
  server_name: "g4v.dev"
  signing_key_path: "/config/signing.key"
  admin_contact: 'mailto:matrix@g4v.dev'
  enable_registration: false
  public_baseurl: https://matrix.g4v.dev/
  app_service_config_files:
    - /config/gitter-registration.yaml
    - /config/instagram-registration.yaml
    - /config/whatsapp-registration.yaml
    - /config/telegram-registration.yaml
  enable_group_creation: true
  trusted_third_party_id_servers:
    - matrix.g4v.dev
  email:
    enable_notifs: false
    notif_from: "Your Friendly %(app)s homeserver <noreply@g4v.dev>"
    client_base_url: "http://chat.g4v.dev"
  password_config:
    enabled: false
  sso:
    client_whitelist:
      - https://chat.g4v.dev
  saml2_config:
    idp_redirect_url: "https://keycloak.g4v.dev/auth/realms/master/protocol/saml"
    sp_config:
      entityid: "matrix-g4v-dev"
      description: "Matrix Server"
      metadata:
        remote:
          - url: https://keycloak.g4v.dev/auth/realms/master/protocol/saml/descriptor
      debug: 0
      key_file: "/config/saml-key.pem"
      cert_file: "/config/saml-cert.pem"
      encryption_keypairs:
        - key_file: "/config/saml-key.pem"
          cert_file: "/config/saml-cert.pem"
      attribute_map_dir: "/config/"
      xmlsec_binary: "/usr/bin/xmlsec1"
      name_form: "urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
      service:
        sp:
          name: "matrix-login"
          endpoints:
            single_sign_on_service:
              - "https://matrix.g4v.dev/_matrix/saml2/authn_response"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            assertion_consumer_service:
              - "https://matrix.g4v.dev/_matrix/saml2/authn_response"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            single_logout_service:
              - "https://matrix.g4v.dev/_matrix/saml2/logout"
              - "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
          required_attributes: ["uid", "mail"]
          optional_attributes: ["displayName"]
          sign_assertion: true
          sign_response: true
          allow_unsolicited: true

logconfig:
  root:
    level: INFO
    handlers: [console]
  loggers:
    shared_secret_authenticator:
      level: INFO
    synapse.access.http.8008:
      level: ERROR
    synapse.federation.transport.server:
      level: ERROR
    synapse.metrics:
      level: ERROR

dnsConfig:
  options:
    - name: ndots
      value: "1"

extraConfigs:
  instagram-registration.yaml:
    id: instagram-puppet
    namespaces:
      users:
        - exclusive: true
          regex: '@puppet-instagram_.*'
      rooms: []
      aliases:
        - exclusive: true
          regex: '#puppet-instagram_.*'
    protocols: []
    rate_limited: false
    sender_localpart: puppet-instagram
    url: https://dev.gavinmogan.com
  gitter-registration.yaml:
    id: gitter
    namespaces:
      users:
        - exclusive: true
          regex: '@appservice-gitter_.*'
      aliases:
        - exclusive: true
          regex: '#appservice-gitter_.*'
      rooms: []
    url: http://matrix-appservice-gitter.matrix.svc.cluster.local:5858
    sender_localpart: appservice-gitter
    rate_limited: true
    protocols: null
  whatsapp-registration.yaml:
    id: whatsapp
    url: http://mautrix-whatsapp.matrix.svc.cluster.local:29318
    sender_localpart: whatsappbot
    rate_limited: false
    namespaces:
      users:
        - regex: ^@whatsapp_[0-9]+:g4v.dev$
          exclusive: true
  telegram-registration.yaml:
    id: telegram
    namespaces:
        users:
        - exclusive: true
          regex: '@telegram_.+:g4v.dev'
        aliases:
        - exclusive: true
          regex: '#telegram_.+:g4v.dev'
    url: http://mautrix-telegram.matrix.svc.cluster.local:29317
    sender_localpart: telegrambot
    rate_limited: false
  map.py: |-
    MAP = {
      "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
      "fro": {
          'uid': 'uid',
          'displayName': 'displayName',
          'mail': 'mail',
      },
      "to": {
          'uid': 'uid',
          'displayName': 'displayName',
          'mail': 'mail',
      }
    }
