repositories:
  - name: codecentric
    url: https://codecentric.github.io/helm-charts

releases:
  - name: keycloak
    chart: codecentric/keycloak
    namespace: keycloak
    values:
      - ./keycloak.yaml
    secrets:
      - ./keycloak-secrets.yaml
