{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zap2xml.serviceAccountName" . }}
  labels:
{{ include "zap2xml.labels" . | indent 4 }}
{{- end -}}
