repositories:
  - name: sstarcher
    url: https://shanestarcher.com/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: wiremind
    url: https://wiremind.github.io/wiremind-helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: monitoring
    values:
      - prometheus.yaml
    secrets:
      - prometheus-secrets.yaml
  - name: helm-exporter
    chart: sstarcher/helm-exporter
    namespace: monitoring
  #- name: prometheus-node-exporter
  #  chart: prometheus-community/prometheus-node-exporter
  #  namespace: monitoring
  - name: kube-state-metrics
    chart: bitnami/kube-state-metrics
    namespace: monitoring
  - name: karma
    chart: wiremind/karma
    namespace: monitoring
    values:
      - karma.yaml
  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    values:
      - grafana.yaml
    secrets:
      - grafana-secrets.yaml
  - name: prometheus-nut-exporter
    chart: k8s-at-home/prometheus-nut-exporter
    namespace: monitoring
    values:
      - env:
          TZ: American/Vancouver
      - resources:
          limits:
            cpu: "10m"
            memory: "16Mi"
          requests:
            cpu: "1m"
            memory: "8Mi"
