repositories:
  - name: sstarcher
    url: https://shanestarcher.com/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: monitoring
    values:
      - prometheus.yaml
  - name: helm-exporter
    chart: sstarcher/helm-exporter
    namespace: monitoring
  #- name: prometheus-node-exporter
  #  chart: prometheus-community/prometheus-node-exporter
  #  namespace: monitoring
  - name: kube-state-metrics
    chart:  bitnami/kube-state-metrics
    namespace: monitoring
