---
helmDefaults:
  cleanupOnFail: true
  wait: true
  timeout: 300
  atomic: true

releases:
  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    values:
      - metrics-server.yaml
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    values:
      - nginx-ingress.yaml
    secrets:
      - nginx-ingress-secrets.yaml
  - name: metallb
    namespace: kube-system
    chart: stable/metallb
