---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: metrics-server
    namespace: kube-system
    chart: bitnami/metrics-server
    values:
      - metrics-server.yaml
  - name: nginx-ingress
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    values:
      - nginx-ingress.yaml
    secrets:
      - nginx-ingress-secrets.yaml
  - name: metallb
    namespace: kube-system
    chart: bitnami/metallb
    values:
      - metallb.yaml
    secrets:
      - metallb-secrets.yaml
  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    values:
      - external-dns.yaml
    secrets:
      - external-dns-secrets.yaml
