repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts

releases:
  - name: goplaxt
    chart: halkeye/goplaxt
    namespace: default
    values:
      - goplaxt.yaml
    secrets:
      - goplaxt-secrets.yaml
  - name: thelounge
    chart: halkeye/thelounge
    namespace: default
    values:
      - thelounge.yaml
  - name: whoami
    chart: halkeye/whoami
    namespace: default
    values:
      - whoami.yaml
  - name: postfix
    chart: halkeye/postfix
    namespace: default
    values:
      - postfix.yaml
    secrets:
      - postfix-secrets.yaml
