releases:
  - name: goplaxt
    chart: halkeye/goplaxt
    namespace: default
    values:
      - goplaxt.yaml
    secrets:
      - ../../secrets/goplaxt.yaml
  - name: redis
    chart: stable/redis
    namespace: default
    values:
      - redis.yaml
    secrets:
      - ../../secrets/redis.yaml
  - name: thelounge
    chart: halkeye/thelounge
    namespace: default
    values:
      - thelounge.yaml
  - name: vouch
    chart: halkeye/vouch
    namespace: default
    values:
      - vouch.yaml
    secrets:
      - vouch-secrets.yaml
  - name: whoami
    chart: halkeye/whoami
    namespace: default
    values:
      - whoami.yaml
  - name: postfix
    chart: halkeye/postfix
    namespace: default
    values:
      - postfix.yaml
    secrets:
      - postfix-secrets.yaml
