---
ingress:
  enabled: true
  hosts:
    - nzbhydra.home.gavinmogan.com
  tls:
    - secretName: nzbhydra-tls
      hosts:
        - nzbhydra.home.gavinmogan.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

persistence:
  enabled: true
  size: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: linstor
