---
timezone: 'America/Vancouver'

image:
  tag: 1.16.2

puid: 1000
guid: 1000

ingress:
  enabled: true
  hosts:
    - host: esphome.home.gavinmogan.com
      paths:
        - path: /
  tls:
    - secretName: esphome-tls
      hosts:
        - esphome.home.gavinmogan.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"

persistence:
  config:
    enabled: true
    storageClass: longhorn

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi
