---
timezone: 'America/Vancouver'

image:
  tag: 1.17.2

puid: 1000
guid: 1000

ingress:
  enabled: true
  hosts:
    - host: esphome.int.g4v.dev
      paths:
        - path: /
  annotations:
    kubernetes.io/ingress.class: internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"

persistence:
  config:
    enabled: true
    storageClass: longhorn

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi
