repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: home-assistant
    chart: k8s-at-home/home-assistant
    namespace: home
    version: 5.1.1
    values:
      - home-assistant.yaml
    #secrets:
    #  - homeassistant-secrets.yaml
  - name: room-assistant
    namespace: home
    chart: halkeye/room-assistant
    values:
      - room-assistant.yaml
    secrets:
      - room-assistant-secrets.yaml
  - name: esphome
    namespace: home
    version: 4.2.1
    chart: k8s-at-home/esphome
    values:
      - esphome.yaml
  - name: ozwdaemon
    namespace: home
    chart: halkeye/ozwdaemon
    values:
      - ozwdaemon.yaml
#  - name: zigbee2mqtt
#    namespace: home
#    chart: k8s-at-home/zigbee2mqtt
#    values:
#      - zigbee2mqtt.yaml
  - name: zwavejs2mqtt
    chart: k8s-at-home/zwavejs2mqtt
    namespace: home
    values:
      - zwavejs2mqtt.yaml
