repositories:
  - name: halkeye
    url: https://halkeye.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: home-assistant
    chart: k8s-at-home/home-assistant
    namespace: home
    values:
      - home-assistant.yaml
    #secrets:
    #  - homeassistant-secrets.yaml
  - name: room-assistant
    namespace: home
    chart: halkeye/room-assistant
    values:
      - room-assistant.yaml
    secrets:
      - room-assistant-secrets.yaml
  - name: esphome
    namespace: home
    chart: k8s-at-home/esphome
    values:
      - esphome.yaml
  - name: ozwdaemon
    namespace: home
    chart: halkeye/ozwdaemon
    values:
      - ozwdaemon.yaml
