apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "discord-rpg-schedule.fullname" . }}
  labels:
{{ include "discord-rpg-schedule.labels" . | indent 4 }}
spec:
  schedule: "15 */3 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "discord-rpg-schedule.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            component: "cron"
        spec:
          restartPolicy: Never
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          serviceAccountName: {{ template "discord-rpg-schedule.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "discord-rpg-schedule.fullname" . }}
              command: ["npm", "run", "start:notifier"]

