apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-rpg-schedule.fullname" . }}
  labels:
{{ include "discord-rpg-schedule.labels" . | indent 4 }}
type: Opaque
data:
  PORT: {{ .Values.service.port | toString | b64enc | quote }}
  HOST: {{ .Values.config.host | toString | b64enc | quote }}
  MONGODB_URL: {{ .Values.config.mongodb_url | toString | b64enc | quote }}
  TOKEN: {{ .Values.config.token | toString | b64enc | quote }}
  CLIENT_ID: {{ .Values.config.client_id | toString | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.config.client_secret | toString | b64enc | quote }}
  DONATE: {{ .Values.config.donate | toString | b64enc | quote }}
  GITHUB: {{ .Values.config.github | toString | b64enc | quote }}
  INVITE: {{ .Values.config.invite | toString | b64enc | quote }}
  AUTH_URL: {{ .Values.config.auth_url | toString | b64enc | quote }}
  RESCHEDULING: {{ .Values.config.rescheduling | toString | b64enc | quote }}
  REMINDERS: {{ .Values.config.reminders | toString | b64enc | quote }}
  MAINTENANCE: {{ .Values.config.maintenance | toString | b64enc | quote }}
  PATREON_API_ACCESS_TOKEN: {{ .Values.config.patreon_api_access_token | toString | b64enc | quote }}
  PATREON_CAMPAIGN_ID: {{ .Values.config.patreon_campaign_id | toString | b64enc | quote }}
