{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "discord-rpg-schedule.serviceAccountName" . }}
  labels:
{{ include "discord-rpg-schedule.labels" . | indent 4 }}
{{- end -}}
