ingress:
  enabled: true
  tls:
    - secretName: selfservice-tls
      hosts:
        - a.g4v.dev
  hosts:
    - host: a.g4v.dev
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
config:
  # Hash mechanism for password:
  # SSHA, SSHA256, SSHA384, SSHA512
  # SHA, SHA256, SHA384, SHA512
  # SMD5
  # MD5
  # CRYPT
  # clear (the default)
  # auto (will check the hash of current password)
  # This option is not used with ad_mode: true
  hash: "auto"

  # LDAP
  ldap_url: "ldap://openldap.openldap.svc.cluster.local"
  ldap_starttls: false
  ldap_binddn: "cn=admin,dc=gavinmogan,dc=com"
  ldap_base: "dc=gavinmogan,dc=com"
  ldap_login_attribute: "uid"
  ldap_fullname_attribute: "cn"
  ldap_filter: "(&(objectClass=person)($ldap_login_attribute={login}))"

  # use pwnedpasswords api v2 to securely check if the password has been on a leak
  use_pwnedpasswords: true

  ## SSH Key Change
  # Allow changing of sshPublicKey?
  change_sshkey: true

  # Notify users anytime their sshPublicKey is changed
  ## Requires mail configuration below
  notify_on_sshkey_change: true

  ## Questions/answers
  # Use questions/answers?
  use_questions: false

  ## Mail
  # LDAP mail attribute
  mail_attribute: "mail"
  # Get mail address directly from LDAP (only first mail entry)
  # and hide mail input field
  # default: false
  mail_address_use_ldap: true
  # Who the email should come from
  mail_from: "accounts.admin@g4v.dev"
  mail_from_name: "Self Service Password"
  mail_signature: ""
  # Notify users anytime their password is changed
  notify_on_change: true
  # PHPMailer configuration (see https://github.com/PHPMailer/PHPMailer)
  mail_protocol: 'smtp'
  mail_smtp_debug: 0
  mail_smtp_auth: false
  mail_smtp_autotls: false
  mail_smtp_secure: false
  mail_smtp_host: 'odin.dhcp.home'
  mail_smtp_user: ''
  mail_smtp_pass: ''
  mail_smtp_port: 25

  ## SMS
  # Use sms
  use_sms: true
  # SMS method (mail, api)
  sms_method: "api"
  sms_api_lib: "lib/smsapi-twilo.inc.php"
  # GSM number attribute
  sms_attribute: "mobile"
  # Partially hide number
  sms_partially_hide_number: true

  # Encryption, decryption keyphrase, required if crypt_tokens: true
  # Please change it to anything long, random and complicated, you do not have to remember it
  # Changing it will also invalidate all previous tokens and SMS codes

  # Reset URL (if behind a reverse proxy)
  reset_url: "https://a.g4v.dev{$_SERVER['SCRIPT_NAME']}"
