repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
  - name: grafana
    chart: stable/grafana
    namespace: grafana
    values:
      - grafana.yaml
    secrets:
      - ../../secrets/grafana.yaml
