---
dnsConfig:
  options:
    - name: ndots
      value: "1"
ingress:
  enabled: true
  hosts:
    - host: whostreaming.halkeye.net
      paths: ['/']
  tls:
    - secretName: whostreaming-tls
      hosts:
        - whostreaming.halkeye.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
config:
  self_url: https://whostreaming.halkeye.net/
