---
apiVersion: v1
kind: Secret
metadata:
  # Jenkins Secrets
  name: "jenkins-secrets"
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
{{ $key | nindent 2 }}: {{ $value | b64enc }}
{{- end }}
